import sqlite3
import os
import urllib.parse
from datetime import datetime, timedelta
from typing import Optional
from dotenv import load_dotenv
from passlib.context import CryptContext
from jose import JWTError, jwt

try:
    import psycopg2
    import psycopg2.extras
except ImportError:
    psycopg2 = None

load_dotenv()

SECRET_KEY = os.getenv("JWT_SECRET", "astrology-ai-super-secret-key-change-in-prod")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # 7 days

pwd_context = CryptContext(schemes=["pbkdf2_sha256"], deprecated="auto")
DB_PATH = "users.db"
DATABASE_URL = os.getenv("DATABASE_URL")

def get_db_connection():
    """Returns (connection, db_type) based on environment."""
    if DATABASE_URL and psycopg2:
        conn = psycopg2.connect(DATABASE_URL, cursor_factory=psycopg2.extras.RealDictCursor)
        conn.autocommit = True
        return conn, "postgres"
    else:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        return conn, "sqlite"

def init_db():
    """Initialize the database (SQLite or PostgreSQL) with users table."""
    conn, db_type = get_db_connection()
    cursor = conn.cursor()
    
    if db_type == "postgres":
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT UNIQUE NOT NULL,
                full_name TEXT NOT NULL,
                hashed_password TEXT NOT NULL,
                plan TEXT DEFAULT 'free',
                created_at TIMESTAMPTZ DEFAULT NOW()
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS birth_profiles (
                user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
                full_name TEXT NOT NULL,
                birth_date TEXT NOT NULL,
                birth_time TEXT NOT NULL,
                city TEXT NOT NULL,
                latitude DOUBLE PRECISION NOT NULL,
                longitude DOUBLE PRECISION NOT NULL,
                timezone TEXT NOT NULL,
                updated_at TIMESTAMPTZ DEFAULT NOW()
            )
        """)
    else:
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                email TEXT UNIQUE NOT NULL,
                full_name TEXT NOT NULL,
                hashed_password TEXT NOT NULL,
                plan TEXT DEFAULT 'free',
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS birth_profiles (
                user_id INTEGER PRIMARY KEY,
                full_name TEXT NOT NULL,
                birth_date TEXT NOT NULL,
                birth_time TEXT NOT NULL,
                city TEXT NOT NULL,
                latitude REAL NOT NULL,
                longitude REAL NOT NULL,
                timezone TEXT NOT NULL,
                updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users (id)
            )
        """)
    
    if db_type == "sqlite":
        conn.commit()
    conn.close()

    # Create a default test user if the database is empty
    if not get_user_by_email("seeker@cosmos.com"):
        create_user("seeker@cosmos.com", "Cosmic Seeker", "password123")


def get_user_by_email(email: str) -> Optional[dict]:
    conn, db_type = get_db_connection()
    cursor = conn.cursor()
    query = "SELECT * FROM users WHERE email = %s" if db_type == "postgres" else "SELECT * FROM users WHERE email = ?"
    cursor.execute(query, (email,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def create_user(email: str, full_name: str, password: str) -> dict:
    hashed = pwd_context.hash(password)
    conn, db_type = get_db_connection()
    cursor = conn.cursor()
    query = "INSERT INTO users (email, full_name, hashed_password) VALUES (%s, %s, %s)" if db_type == "postgres" else "INSERT INTO users (email, full_name, hashed_password) VALUES (?, ?, ?)"
    cursor.execute(query, (email, full_name, hashed))
    if db_type == "sqlite":
        conn.commit()
    conn.close()
    return get_user_by_email(email)


def verify_password(plain: str, hashed: str) -> bool:
    return pwd_context.verify(plain, hashed)


def get_user_profile(user_id: int) -> Optional[dict]:
    conn, db_type = get_db_connection()
    cursor = conn.cursor()
    query = "SELECT * FROM birth_profiles WHERE user_id = %s" if db_type == "postgres" else "SELECT * FROM birth_profiles WHERE user_id = ?"
    cursor.execute(query, (user_id,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def save_user_profile(user_id: int, data: dict) -> dict:
    conn, db_type = get_db_connection()
    cursor = conn.cursor()
    if db_type == "postgres":
        query = """
            INSERT INTO birth_profiles 
            (user_id, full_name, birth_date, birth_time, city, latitude, longitude, timezone) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(user_id) DO UPDATE SET 
                full_name=excluded.full_name,
                birth_date=excluded.birth_date,
                birth_time=excluded.birth_time,
                city=excluded.city,
                latitude=excluded.latitude,
                longitude=excluded.longitude,
                timezone=excluded.timezone,
                updated_at=NOW()
        """
    else:
        query = """
            INSERT INTO birth_profiles 
            (user_id, full_name, birth_date, birth_time, city, latitude, longitude, timezone) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(user_id) DO UPDATE SET 
                full_name=excluded.full_name,
                birth_date=excluded.birth_date,
                birth_time=excluded.birth_time,
                city=excluded.city,
                latitude=excluded.latitude,
                longitude=excluded.longitude,
                timezone=excluded.timezone,
                updated_at=CURRENT_TIMESTAMP
        """
    cursor.execute(query, (
        user_id, data['full_name'], data['date'], data['time'], 
        data['city'], data['lat'], data['lon'], data['timezone']
    ))
    if db_type == "sqlite":
        conn.commit()
    conn.close()
    return get_user_profile(user_id)


def create_access_token(data: dict) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode["exp"] = expire
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def decode_access_token(token: str) -> Optional[dict]:
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except JWTError:
        return None
